### ISSUE TITLE
MODX3S: Thumbnails not generating 

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#15]
When adding images, the following error occurs:

[2021-06-25 14:08:58] (ERROR @ /var/www/html/public/core/components/mediamanager/processors/mgr/thumbnail.class.php : 5) PHP warning: require_once(/var/www/html/public/core/model/phpthumb/modphpthumb.class.php): failed to open stream: No such file or directory

In MODX3S this folder (phpthumb) does not exist.

To test it out, I copied the folder from another MODX 2.x branch and pasted it in there. Errors disappeared, but the thumbnails still are not generated. I am assuming MODX3 is using phpthumb in a different way.

**Comment by sonicpunk** [comment]
This works. Can be closed.

**Comment by sonicpunk** [comment]
@ilyautkin This issue is again there. It was fixed before.

**Comment by sonicpunk** [comment]
https://github.com/Sterc/mediamanager/commit/bbf5db557b6b5a729b2abbd05c9b98fada718b12

**Comment by sonicpunk** [comment]
@ilyautkin seems this is a MODX v2 vs v3S thing. Maybe it was reverted because of MODX v2?

Is there a good way for checking this?

**Comment by ilyautkin** [comment]
@sonicpunk fixed in `0.2.8` - https://github.com/Sterc/mediamanager/commit/0bd12d0306a135f378b5222f72c694727dcfc2ee#diff-2a44655479a1a428c31dcf923e0d6f23b43918e2c357cd6fbc48b19895c225a7R27

**Comment by sonicpunk** [comment]
@ilyautkin Still getting the error. In line 31, you are still expecting the 'model/phpthumb/' to exist, which in MODX3 it does not. 

`$this->modx->getOption('core_path', null, MODX_CORE_PATH) . 'model/phpthumb/'`

The only way to have it work is to not set the path.

**Comment by ilyautkin** [comment]
@sonicpunk yes, this should work on MODX2 and MODX3S
https://github.com/Sterc/mediamanager/commit/d2692c721e522380d7c442f0ff7af97207e04503#diff-2a44655479a1a428c31dcf923e0d6f23b43918e2c357cd6fbc48b19895c225a7R31

**Comment by sonicpunk** [comment]
@ilyautkin on my local environment in MODX3S it works now. Thanks!
